[project]
name = "gaokao-school"
version = "0.1.0"
description = "高考学校录取分数线爬虫工具"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.31.0",
    "pandas>=2.0.0",
    "openpyxl>=3.1.0",
    "tk-db-utils>=0.1.3",
    "tk-base-utils>=0.1.4",
]
